[package]
name = "practical_ex1"
version = "0.1.0"
authors = ["Daniel Kerbel <nmdanny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4"
anyhow = "1.0"
pretty_env_logger = "0.4"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
rand = "0.7.3"
tonic = "0.3.1"
# for tonic(&hyper)
prost = "0.6"
parking_lot = "0.11.0"

[lib]
name = "dist_lib"
path = "src/lib.rs"

[[bin]]
name = "runner"
path = "src/runner.rs"

[build-dependencies]
tonic-build = "0.3"