[package]
name = "practical_ex1"
version = "0.1.0"
authors = ["Daniel Kerbel <nmdanny@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
log = "0.4"
pretty_env_logger = "0.4"
futures = "0.3"
tokio = { version = "0.3", features = ["full"] }
tokio-util = { version = "0.4.0", features = ["codec"]}
tokio-serde = { version = "0.6.1", features = ["json"]}
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
rand = "0.7.3"

[lib]
name = "dist_lib"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"